name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: maven:3.8.4-openjdk-17

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: mvn test
